import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/custom_components/Navbar";
import Footer from "@/custom_components/Footer";
import SiteBanner from "@/custom_components/SiteBanner";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QuizCrow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon_.ico", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <SiteBanner />
        <Navbar></Navbar>
        <div className="pt-10">{children}</div>
        <Toaster richColors/>
        <Footer></Footer>
      </body>
    </html>
  );
}
